import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="iris">
          <NavBar></NavBar>
          <main>{children}</main>
<<<<<<< HEAD
          {/* <ThemePanel/> */}
=======
          <ThemePanel />
>>>>>>> 6ef1af1c17f2a9262249b5f5eb6cf24f54d083a0
        </Theme>
      </body>
    </html>
  );
}
